export function Introtext() {
  return (
    <div className="intro">
      <div className="intro__image"></div>
      <div className="intro__container">
        <h1 className="intro__heading">Welcome to holidaze</h1>
        <p className="intro__text">
          Need a place to stay while in Bergen ? we have got you covered, see all the best places to stay in Bergen. We will contact the
          hotel/accommodation for you, and make the best deal available.
        </p>
      </div>
    </div>
  );
}
